package com.application.agent_ekr.lmm.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param model Name of the model to generate completions.
 * @param messages Array of messages between the user and the model.
 * @param functionCall Mode of function calling ('none', 'auto', or specific function name).
 * @param functions Optional custom functions descriptions.
 * @param temperature Sampling temperature; higher values increase randomness.
 * @param topP Alternative sampling parameter controlling probability mass.
 * @param stream Whether to stream results incrementally.
 * @param maxTokens Maximum number of tokens to generate.
 * @param repetitionPenalty Penalization factor for repeated words.
 * @param updateInterval Interval between streaming updates.
 */
@Serializable
class ChatCompletionsRequest(
    @SerialName("model") val model: String,
    @SerialName("messages") val messages: List<Message>,
    @SerialName("function_call") val functionCall: String?,
    @SerialName("functions") val functions: List<CustomFunction>?,
    @SerialName("temperature") val temperature: Double?,
    @SerialName("top_p") val topP: Double?,
    @SerialName("stream") val stream: Boolean?,
    @SerialName("max_tokens") val maxTokens: Int?,
    @SerialName("repetition_penalty") val repetitionPenalty: Double?,
    @SerialName("update_interval") val updateInterval: Double?
)

/**
 * Single message exchanged between the user and the model.
 *
 * @param role Role of the sender ('system', 'user', 'assistant', 'function').
 * @param content Textual content of the message.
 * @param functionsStateId Identifier linking related function calls.
 * @param attachments Identifiers of attached files.
 */
@Serializable
class Message(
    @SerialName("role") val role: String,
    @SerialName("content") val content: String,
    @SerialName("functions_state_id") val functionsStateId: String?,
    @SerialName("attachments") val attachments: List<String>?
)

/**
 * Describes a custom function available for invocation during generation.
 *
 * @param name Name of the custom function.
 * @param description Description of what the function does.
 * @param parameters Schema defining expected input parameters.
 */
@Serializable
data class CustomFunction(
    @SerialName("name") val name: String,
    @SerialName("description") val description: String,
    @SerialName("parameters") val parameters: ParametersSchema,
    @SerialName("return_parameters") val returnParameters: ReturnParamsSchema?,
    @SerialName("few_shot_examples") val fewShotExamples: List<FewShotExample>?
)

/**
 * Defines the schema for input parameters of a custom function.
 *
 * @param type Type of the schema (usually 'object').
 * @param required Required fields in the schema.
 */
@Serializable
data class ParametersSchema(
    @SerialName("type") val type: String,
    @SerialName("properties") val properties: Map<String, PropertyDefinition>,
    @SerialName("required") val required: List<String>?
)

/**
 * Definition of a property in the parameters schema.
 *
 * @param type Type of the field (e.g., 'string', 'number').
 * @param description Human-readable explanation of the field.
 * @param format Formatting details (e.g., 'date-time').
 * @param enum Possible enumerated values.
 */
@Serializable
data class PropertyDefinition(
    @SerialName("type") val type: String,
    @SerialName("description") val description: String,
    @SerialName("format") val format: String?,
    @SerialName("enum") val enum: List<String>?
)

/**
 * Defines the schema for return parameters of a custom function.
 *
 * @param type Type of the schema (usually 'object').
 */
@Serializable
data class ReturnParamsSchema(
    @SerialName("type") val type: String,
    @SerialName("properties") val properties: Map<String, PropertyDefinition>
)

/**
 * Example pair showing how a custom function should be invoked.
 *
 * @param request User's request triggering the function.
 * @param params Arguments passed to the function.
 */
@Serializable
data class FewShotExample(
    @SerialName("request") val request: String,
    @SerialName("params") val params: Map<String, String>
)

/**
 * Response received from the `/chat/completions` endpoint.
 *
 * @param choices Generated completions.
 * @param created Timestamp of creation.
 * @param model Used model identifier.
 * @param usage Information about token usage.
 */
@Serializable
class ChatCompletionsResponse(
    @SerialName("choices") val choices: List<Choice>,
    @SerialName("created") val created: Long,
    @SerialName("model") val model: String,
    @SerialName("usage") val usage: UsageTokens
)

/**
 * Individual choice generated by the model.
 *
 * @param message Generated message.
 * @param index Index of the choice.
 * @param finishReason Reason why generation stopped.
 */
@Serializable
class Choice(
    @SerialName("message") val message: Message,
    @SerialName("index") val index: Int,
    @SerialName("finish_reason") val finishReason: String
)

/**
 * Details about token usage in the response.
 *
 * @param promptTokens Number of tokens in the prompt.
 * @param completionTokens Number of tokens in the completion.
 * @param totalTokens Total number of tokens processed.
 */
@Serializable
class UsageTokens(
    @SerialName("prompt_tokens") val promptTokens: Int,
    @SerialName("completion_tokens") val completionTokens: Int,
    @SerialName("total_tokens") val totalTokens: Int
)
