package com.application.agent_ekr.lmm.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Request for chat completions.
 *
 * @property model Model name.
 * @property messages List of messages.
 * @property functionCall Function call settings.
 * @property functions Available custom functions.
 * @property temperature Temperature setting.
 * @property topP Top-P sampling threshold.
 * @property stream Streaming flag.
 * @property maxTokens Maximum number of tokens.
 * @property repetitionPenalty Repetition penalty.
 * @property updateInterval Update interval for streaming.
 */
@Serializable
class ChatCompletionsRequest(
    @SerialName("model") val model: String,
    @SerialName("messages") val messages: List<Message>,
    @SerialName("function_call") val functionCall: String?,
    @SerialName("functions") val functions: List<CustomFunction>?,
    @SerialName("temperature") val temperature: Double?,
    @SerialName("top_p") val topP: Double?,
    @SerialName("stream") val stream: Boolean?,
    @SerialName("max_tokens") val maxTokens: Int?,
    @SerialName("repetition_penalty") val repetitionPenalty: Double?,
    @SerialName("update_interval") val updateInterval: Double?
)

/**
 * Describes a custom function.
 *
 * @property name Function name.
 * @property description Function description.
 * @property parameters Input parameters schema.
 * @property returnParameters Output parameters schema.
 * @property fewShotExamples Examples of function usage.
 */
@Serializable
class CustomFunction(
    @SerialName("name") val name: String,
    @SerialName("description") val description: String,
    @SerialName("parameters") val parameters: ParametersSchema,
    @SerialName("return_parameters") val returnParameters: ReturnParamsSchema?,
    @SerialName("few_shot_examples") val fewShotExamples: List<FewShotExample>?
)

/**
 * Defines the input parameters schema.
 *
 * @property type Schema type.
 * @property properties Properties map.
 * @property required Required fields.
 */
@Serializable
class ParametersSchema(
    @SerialName("type") val type: String,
    @SerialName("properties") val properties: Map<String, PropertyDefinition>,
    @SerialName("required") val required: List<String>?
)

/**
 * Defines the return parameters schema.
 *
 * @property type Schema type.
 * @property properties Properties map.
 */
@Serializable
class ReturnParamsSchema(
    @SerialName("type") val type: String,
    @SerialName("properties") val properties: Map<String, PropertyDefinition>
)

/**
 * Single message exchanged between the user and the model.
 *
 * @param role Role of the sender ('system', 'user', 'assistant', 'function').
 * @param content Textual content of the message.
 * @param functionsStateId Identifier linking related function calls.
 * @param attachments Identifiers of attached files.
 */
@Serializable
class Message(
    @SerialName("role") val role: Role,
    @SerialName("content") val content: String,
    @SerialName("functions_state_id") val functionsStateId: String?,
    @SerialName("attachments") val attachments: List<String>?
)

/**
 * Definition of a property in the parameters schema.
 *
 * @param type Type of the field (e.g., 'string', 'number').
 * @param description Human-readable explanation of the field.
 * @param format Formatting details (e.g., 'date-time').
 * @param enum Possible enumerated values.
 */
@Serializable
class PropertyDefinition(
    @SerialName("type") val type: String,
    @SerialName("description") val description: String,
    @SerialName("format") val format: String?,
    @SerialName("enum") val enum: List<String>?
)

/**
 * Response received from the `/chat/completions` endpoint.
 *
 * @param choices Generated completions.
 * @param created Timestamp of creation.
 * @param model Used model identifier.
 * @param usage Information about token usage.
 */
@Serializable
class ChatCompletionsResponse(
    @SerialName("choices") val choices: List<Choice>,
    @SerialName("created") val created: Long,
    @SerialName("model") val model: String,
    @SerialName("usage") val usage: UsageTokens
)

/**
 * Individual choice generated by the model.
 *
 * @param message Generated message.
 * @param index Index of the choice.
 * @param finishReason Reason why generation stopped.
 */
@Serializable
class Choice(
    @SerialName("message") val message: Message,
    @SerialName("index") val index: Int,
    @SerialName("finish_reason") val finishReason: String
)
