package com.application.agent_ekr.gigachat.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Individual choice generated by the model.
 *
 * @param message Generated message.
 * @param index Index of the choice.
 * @param finishReason Reason why generation stopped.
 */
@Serializable
class ChatCompletionChoice(
    @SerialName("message") val message: Message,
    @SerialName("index") val index: Int,
    @SerialName("finish_reason") val finishReason: String
)
